package doclist

import "github.com/charmbracelet/lipgloss"

// Styles contains style definitions for this list component. By default, these
// values are generated by DefaultStyles.
type Styles struct {
	Table    lipgloss.Style
	Doc      lipgloss.Style
	Selected lipgloss.Style
}

func defaultStyles() Styles {
	return Styles{
		Table:    lipgloss.NewStyle().BorderStyle(lipgloss.ThickBorder()).BorderForeground(lipgloss.Color("240")),
		Selected: lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("212")),
		Doc: lipgloss.NewStyle().
			BorderStyle(lipgloss.ThickBorder()).BorderForeground(lipgloss.Color("57")),
	}
}
