package doclist

import "github.com/charmbracelet/lipgloss"

// Styles contains style definitions for this list component. By default, these
// values are generated by DefaultStyles.
type Styles struct {
	Doc      lipgloss.Style
	Selected lipgloss.Style
}

func defaultStyles() Styles {
	return Styles{
		Selected: lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("212")),
		Doc:      lipgloss.NewStyle().Padding(0, 1),
	}
}
