package modal

import "github.com/charmbracelet/lipgloss"

// Styles contains style definitions for this list component. By default, these
// values are generated by DefaultStyles.
type Styles struct {
	Modal              lipgloss.Style
	ErrorHeader        lipgloss.Style
	ConfirmationHeader lipgloss.Style
	Button             lipgloss.Style
	HighlightedButton  lipgloss.Style
	InputTextBox       lipgloss.Style
	InputTextBoxMsg    lipgloss.Style
}

func defaultStyles() Styles {
	return Styles{
		Modal: lipgloss.NewStyle().
			BorderStyle(lipgloss.RoundedBorder()).
			BorderForeground(lipgloss.Color("6")).
			Width(40).
			AlignHorizontal(lipgloss.Center),
		ErrorHeader: lipgloss.NewStyle().
			Bold(true).
			Foreground(lipgloss.Color("9")),
		ConfirmationHeader: lipgloss.NewStyle().
			Bold(true).
			Foreground(lipgloss.Color("10")),
		Button: lipgloss.NewStyle().
			Height(0).
			Width(4).
			BorderStyle(lipgloss.RoundedBorder()).
			AlignHorizontal(lipgloss.Center).
			BorderForeground(lipgloss.Color("6")),
		HighlightedButton: lipgloss.NewStyle().
			Height(0).
			Width(4).
			BorderStyle(lipgloss.ThickBorder()).
			AlignHorizontal(lipgloss.Center).
			BorderForeground(lipgloss.Color("57")),
		InputTextBoxMsg: lipgloss.NewStyle().
			AlignHorizontal(lipgloss.Center).
			Height(3).
			Width(40),
		InputTextBox: lipgloss.NewStyle().
			AlignHorizontal(lipgloss.Left).
			Width(40),
	}
}
