package modal

import "github.com/charmbracelet/lipgloss"

// Styles contains style definitions for this list component. By default, these
// values are generated by DefaultStyles.
type Styles struct {
	Modal          lipgloss.Style
	ErrorHeader    lipgloss.Style
	DeletionHeader lipgloss.Style
}

func defaultStyles() Styles {
	return Styles{
		Modal: lipgloss.NewStyle().
			Border(lipgloss.RoundedBorder(), true).
			BorderForeground(lipgloss.Color("6")).
			Padding(0, 1).
			Width(40).
			AlignHorizontal(lipgloss.Center),
		ErrorHeader: lipgloss.NewStyle().
			Bold(true).
			Foreground(lipgloss.Color("9")),
		DeletionHeader: lipgloss.NewStyle().
			Bold(true).
			Foreground(lipgloss.Color("10")),
	}
}
