name: Release
on:
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goarch: [amd64, arm64]
        goos: [linux, darwin]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build
        run: |
          GOARCH=${{ matrix.goarch }} GOOS=${{ matrix.goos }} go build -ldflags "-X 'github.com/kreulenk/mongotui/internal/build.Version=${{ github.ref_name }}' -X 'github.com/kreulenk/mongotui/internal/build.SHA=$(git rev-parse HEAD)'" -o mongotui ./main.go

      - name: Archive build
        run: |
          tar -czvf mongotui-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz mongotui

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./mongotui-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
          asset_name: mongotui-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
          asset_content_type: application/gzip

  homebrew:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout homebrew-brew repository
        uses: actions/checkout@v4
        with:
          repository: kreulenk/homebrew-brew
          token: ${{ secrets.BREW_PAT }}
          ref: main

      - name: Download Release Assets
        run: |
          curl -L -o mongotui-darwin-amd64.tar.gz https://github.com/kreulenk/mongotui/releases/download/${{ github.ref_name }}/mongotui-darwin-amd64.tar.gz
          curl -L -o mongotui-darwin-arm64.tar.gz https://github.com/kreulenk/mongotui/releases/download/${{ github.ref_name }}/mongotui-darwin-arm64.tar.gz

      - name: Update Homebrew formula
        run: |
          cat <<EOF > Formula/mongotui.rb
          class Mongotui < Formula
            desc "A TUI for MongoDB"
            homepage "https://github.com/kreulenk/mongotui"
            url "https://github.com/kreulenk/mongotui/releases/download/${{ github.ref_name }}/mongotui-darwin-amd64.tar.gz"
            sha256 "$(shasum -a 256 mongotui-darwin-amd64.tar.gz | awk '{print $1}')"
            version "${{ github.ref_name }}"

            if Hardware::CPU.arm?
              url "https://github.com/kreulenk/mongotui/releases/download/${{ github.ref_name }}/mongotui-darwin-arm64.tar.gz"
              sha256 "$(shasum -a 256 mongotui-darwin-arm64.tar.gz | awk '{print $1}')"
            end

            def install
              bin.install "mongotui"
            end

            test do
              system "#{bin}/mongotui"
            end
          end
          EOF

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://${{ secrets.BREW_PAT }}@github.com/kreulenk/homebrew-brew.git
          git add Formula/mongotui.rb
          git commit -m "Update homebrew to point to latest mongotui release"
          git push origin main
        env:
          BREW_PAT_TOKEN: ${{ secrets.BREW_PAT }}